server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  application:
    name: eureka-server
  config:
    import: 'optional:configserver:http://config-server:8071'
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://zipkin:9411
