example:
  property: I AM THE DEFAULT
  location: git microservices-properties
spring:
  datasource:
    platform: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
